// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tonepie.Server.Data;

#nullable disable

namespace Tonepie.Server.Migrations.Postgres
{
    [DbContext(typeof(PostgresTonepieDb))]
    partial class PostgresTonepieDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tonepie.Server.Data.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("BinLimitVisits")
                        .HasColumnType("integer");

                    b.Property<long>("BinSince")
                        .HasColumnType("bigint");

                    b.Property<int>("BinVisits")
                        .HasColumnType("integer");

                    b.Property<string>("Firmware")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("FirstSeen")
                        .HasColumnType("bigint");

                    b.Property<long>("LastSeen")
                        .HasColumnType("bigint");

                    b.Property<long>("LitterAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Tonepie.Server.Data.DeviceCat", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("WeightG")
                        .HasColumnType("integer");

                    b.HasKey("DeviceId", "Index");

                    b.ToTable("DeviceCats", (string)null);
                });

            modelBuilder.Entity("Tonepie.Server.Data.MaintenanceEvent", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint");

                    b.HasKey("DeviceId", "Kind", "Epoch");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Tonepie.Server.Data.Visit", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("character varying(40)");

                    b.Property<int>("EspId")
                        .HasColumnType("integer");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint");

                    b.Property<string>("CatName")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("DurationS")
                        .HasColumnType("integer");

                    b.Property<bool>("Manual")
                        .HasColumnType("boolean");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("WeightG")
                        .HasColumnType("integer");

                    b.HasKey("DeviceId", "EspId", "Epoch");

                    b.HasIndex("DeviceId", "Epoch");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Tonepie.Server.Data.DeviceCat", b =>
                {
                    b.HasOne("Tonepie.Server.Data.Device", null)
                        .WithMany("Cats")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tonepie.Server.Data.MaintenanceEvent", b =>
                {
                    b.HasOne("Tonepie.Server.Data.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tonepie.Server.Data.Visit", b =>
                {
                    b.HasOne("Tonepie.Server.Data.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tonepie.Server.Data.Device", b =>
                {
                    b.Navigation("Cats");
                });
#pragma warning restore 612, 618
        }
    }
}
