#pragma once
#include <Arduino.h>
// MCU developer page served at "/dev". Language shared with the home page (localStorage "lang").
const char WEB_UI[] PROGMEM = R"HTML(<!doctype html>
<html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tonepie · dev</title><link rel="icon" type="image/png" href="/icon-192.png"><style>
:root{color-scheme:dark;--muted:#a9bbcb;--accent:#74dfca}*{box-sizing:border-box}body{margin:0;background:#0c1720;color:#eef5f8;font:16px system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:28px 18px}h1{font-size:32px;margin:8px 0}h2{font-size:20px;margin-top:0}.muted,small{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px}.card{background:#152630;border:1px solid #2b414d;border-radius:16px;padding:20px;margin:16px 0}.grid .card{margin:0}button,input,select{font:inherit;border-radius:8px;padding:11px;border:1px solid #48616f;background:#203947;color:white}button{cursor:pointer;margin:5px 5px 5px 0}button.primary{background:var(--accent);color:#09261e}button:disabled{opacity:.4;cursor:not-allowed}label{display:block;margin:12px 0}input[type=number],input[type=password],input[type=file],input:not([type]){width:100%}.metrics{display:flex;gap:20px;flex-wrap:wrap}.metric strong{display:block;font-size:23px}.table{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;border-bottom:1px solid #30444f;padding:10px;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:320px;overflow:auto;font-size:12px}#notice{position:sticky;bottom:12px;background:#234337;padding:14px;border-radius:10px;min-height:48px}.warning{color:#ffd792}a{color:var(--accent)}.top{display:flex;justify-content:space-between;align-items:center;gap:10px}.top button{margin:0;padding:6px 12px;font-weight:700}
</style></head><body><main><div class="top"><small><span data-t="crumb"></span> · <a href="/" data-t="home"></a></small><button id="lang"></button></div><h1 data-t="title"></h1><p class="muted" data-t="intro"></p>
<section class="card metrics"><div class="metric"><small data-t="mLink"></small><strong id="link"></strong></div><div class="metric"><small>Wi-Fi / IP</small><strong id="ip">—</strong></div><div class="metric"><small data-t="mState"></small><strong id="state"></strong></div><div class="metric"><small data-t="mFault"></small><strong id="fault"></strong></div></section>
<div class="grid"><section class="card"><h2 data-t="commands"></h2><p class="warning" data-t="cmdWarn"></p><label><input id="arm" type="checkbox"> <span data-t="arm"></span></label><button class="primary write" data-action="clean" data-t="clean"></button><button class="write" data-action="empty" data-t="empty"></button><p><button class="write" data-action="auto_on">Auto-clean ON</button><button class="write" data-action="auto_off">Auto-clean OFF</button></p><button id="query" data-t="query"></button><p class="muted" id="command"></p><small data-t="cmdNote"></small></section>
<section class="card"><h2 data-t="times"></h2><form id="settings"><label><span data-t="setting"></span><select id="setting"><option value="117" data-t="o117"></option><option value="118" data-t="o118"></option></select></label><label><span data-t="minutes"></span><input id="value" type="number" min="0" max="60" value="5" required></label><button class="primary write" type="submit" data-t="sendSetting"></button></form><p class="muted" data-t="timesNote"></p></section></div>
<section class="card"><h2 data-t="dpTitle"></h2><small data-t="dpNote"></small><div class="table"><table><thead><tr><th>DP</th><th data-t="thLabel"></th><th data-t="thType"></th><th data-t="thValue"></th><th data-t="thAge"></th></tr></thead><tbody id="dps"></tbody></table></div><p id="stats" class="muted"></p></section>
<section class="card"><h2 data-t="otaTitle"></h2><p class="muted" data-t="otaText"></p><form id="ota"><label><span data-t="file"></span><input id="otaFile" type="file" accept=".bin" required></label><label><span data-t="otaPass"></span><input id="otaPass" type="password" autocomplete="off" required></label><button class="primary" type="submit" data-t="otaGo"></button></form></section>
<section class="card"><h2 data-t="wifiTitle"></h2><p class="muted"><span data-t="current"></span> <b id="ssid">—</b><span id="ap"></span>. <span data-t="wifiText"></span></p><form id="wifi"><label><span data-t="newSsid"></span><input id="wifiSsid" maxlength="32" required></label><label><span data-t="newPass"></span><input id="wifiPass" type="password" minlength="8" maxlength="63" autocomplete="off" required></label><label><span data-t="otaPass"></span><input id="wifiOta" type="password" autocomplete="off" required></label><button class="primary" type="submit" data-t="wifiGo"></button></form></section>
<section class="card"><h2 data-t="logTitle"></h2><p class="muted" data-t="logNote"></p><pre id="logs"></pre></section><div id="notice" role="status" aria-live="polite"></div></main>
<script>
const TEXT={
it:{crumb:'TONEPIE / TI PRO 25 · ESP-C3 · PAGINA SVILUPPATORE MCU',home:'torna alla home',title:'Controllo locale',intro:'La MCU originale gestisce movimenti e sensori. Mappatura comunitaria: da verificare sulla tua revisione.',
  mLink:'Collegamento MCU',mState:'Stato DP24 grezzo',mFault:'Fault DP22 grezzo',commands:'Comandi',cmdWarn:'Prima prova sorvegliata, lettiera senza animale. Un comando trasmesso non dimostra che il movimento sia avvenuto.',
  arm:'Abilita invii per 10 minuti',clean:'Pulizia manuale',empty:'Svuotamento',query:'Aggiorna dalla MCU',cmdNote:'Gli invii richiedono un DP ricevuto con tipo corretto e recente. Nessun riavvio o bypass sensori.',
  times:'Tempi di pulizia',setting:'Impostazione',o117:'Attesa dopo uscita · DP117',o118:'Intervallo minimo · DP118',minutes:'Minuti',sendSetting:'Invia impostazione',timesNote:'DP117: 0–60 min. DP118: 0–120 min. Il valore attuale si legge nella tabella.',
  dpTitle:'Datapoint ricevuti',dpNote:'ENUM è l’indice UART: non viene tradotto in nomi senza una verifica. Età = tempo dall’ultimo report.',thLabel:'Indicazione comunitaria',thType:'Tipo UART',thValue:'Valore',thAge:'Età',
  otaTitle:'Aggiornamento firmware via rete',otaText:'Carica il file firmware.bin compilato. Serve la password di aggiornamento scritta in include/secrets.h. Al termine il modulo si riavvia; dati di gatti e visite restano salvati.',
  file:'File',otaPass:'Password di aggiornamento',otaGo:'Aggiorna firmware',wifiTitle:'Rete Wi-Fi',current:'Rete attuale:',
  wifiText:'Se il Wi-Fi di casa resta irraggiungibile per 3 minuti il modulo apre la rete di recupero Tonepie-Setup (stessa password del Wi-Fi scritto nel firmware): collegati e apri http://192.168.4.1/dev.',
  newSsid:'Nome della nuova rete',newPass:'Password della rete',wifiGo:'Salva rete e riavvia',logTitle:'Log seriale recente',logNote:'Frame RX/TX validi, errori e rete · estratti hex fino a 64 byte · ultimi 60 eventi',
  waiting:'In attesa',notReceived:'Non ricevuto',connected:'Connessa',init:'Inizializzazione',offline:'Offline',dashOffline:'Dashboard offline',recovery:' · rete di recupero attiva',
  connecting:'Connessione alla dashboard…',ready:'Dashboard connessa. Invii inizialmente disabilitati.',lost:'Connessione persa: non ripetere un movimento senza verificarlo sulla lettiera.',
  askMove:n=>'Avviare '+n+'? Verifica che la lettiera sia libera.',askWifi:n=>'Salvare la rete '+n+' e riavviare?',wifiLost:'Collegamento interrotto: il modulo si sta probabilmente riavviando.',
  askOta:n=>'Sostituire il firmware con '+n+'?',sendingOta:'Invio del firmware in corso: non chiudere la pagina…',otaLost:'Collegamento interrotto durante l’aggiornamento: ricarica la pagina e controlla la versione.',
  stats:s=>`Frame: ${s.frames} · checksum errati: ${s.bad_checksum} · lunghezze errate: ${s.bad_length} · timeout: ${s.timeouts} · DP malformati: ${s.bad_dp} · RAM libera: ${s.heap} B · uptime: ${s.uptime_s} s · causa ultimo reset (codice ESP): ${s.reset_reason}`,
  other:'EN'},
en:{crumb:'TONEPIE / TI PRO 25 · ESP-C3 · MCU DEVELOPER PAGE',home:'back to home',title:'Local control',intro:'The original MCU runs motors and sensors. Community mapping: verify it on your unit.',
  mLink:'MCU link',mState:'Raw DP24 state',mFault:'Raw DP22 fault',commands:'Commands',cmdWarn:'First test under supervision, with no animal in the litter box. A command sent does not prove the movement happened.',
  arm:'Enable sending for 10 minutes',clean:'Manual clean',empty:'Empty',query:'Refresh from MCU',cmdNote:'Sending needs a recent DP of the right type. No restarts or sensor bypasses.',
  times:'Cleaning times',setting:'Setting',o117:'Wait after exit · DP117',o118:'Minimum interval · DP118',minutes:'Minutes',sendSetting:'Send setting',timesNote:'DP117: 0–60 min. DP118: 0–120 min. The current value is in the table.',
  dpTitle:'Datapoints received',dpNote:'ENUM is the UART index: not turned into names without verification. Age = time since the last report.',thLabel:'Community label',thType:'UART type',thValue:'Value',thAge:'Age',
  otaTitle:'Firmware update over the network',otaText:'Upload the compiled firmware.bin. It needs the update password from include/secrets.h. The module restarts at the end; cats and visits stay saved.',
  file:'File',otaPass:'Update password',otaGo:'Update firmware',wifiTitle:'Wi-Fi network',current:'Current network:',
  wifiText:'If the home Wi-Fi stays unreachable for 3 minutes the module opens the recovery network Tonepie-Setup (same password as the Wi-Fi built into the firmware): join it and open http://192.168.4.1/dev.',
  newSsid:'New network name',newPass:'Network password',wifiGo:'Save network and restart',logTitle:'Recent serial log',logNote:'Valid RX/TX frames, errors and network · hex excerpts up to 64 bytes · last 60 events',
  waiting:'Waiting',notReceived:'Not received',connected:'Connected',init:'Initialising',offline:'Offline',dashOffline:'Dashboard offline',recovery:' · recovery network on',
  connecting:'Connecting to the dashboard…',ready:'Dashboard connected. Sending disabled at start.',lost:'Connection lost: do not repeat a movement without checking the litter box.',
  askMove:n=>'Start '+n+'? Make sure the litter box is empty.',askWifi:n=>'Save network '+n+' and restart?',wifiLost:'Connection dropped: the module is probably restarting.',
  askOta:n=>'Replace the firmware with '+n+'?',sendingOta:'Sending the firmware: do not close the page…',otaLost:'Connection dropped during the update: reload the page and check the version.',
  stats:s=>`Frames: ${s.frames} · bad checksums: ${s.bad_checksum} · bad lengths: ${s.bad_length} · timeouts: ${s.timeouts} · malformed DPs: ${s.bad_dp} · free RAM: ${s.heap} B · uptime: ${s.uptime_s} s · last reset reason (ESP code): ${s.reset_reason}`,
  other:'IT'}};
let LANG=(()=>{try{const l=localStorage.getItem('lang');if(TEXT[l])return l}catch(e){}return /^it\b/i.test(navigator.language||'')?'it':'en'})();
const t=(k,...a)=>{const v=TEXT[LANG][k];return typeof v==='function'?v(...a):v};
let token='',busy=false,last=0,stateSeen=false;const $=id=>document.getElementById(id);const say=m=>$('notice').textContent=m;
function applyLang(){document.documentElement.lang=LANG;document.querySelectorAll('[data-t]').forEach(e=>e.textContent=t(e.dataset.t));$('lang').textContent=t('other');
  if(!stateSeen){$('link').textContent=t('waiting');$('state').textContent=$('fault').textContent=t('notReceived');say(t('connecting'))}}
$('lang').onclick=()=>{LANG=LANG==='it'?'en':'it';try{localStorage.setItem('lang',LANG)}catch(e){}applyLang();refresh()};
const H=extra=>Object.assign({'X-Tonepie-Token':token,'X-Tonepie-Lang':LANG},extra);
async function post(path,data){if(busy)return;busy=true;try{let r=await fetch(path,{method:'POST',headers:H({'Content-Type':'application/x-www-form-urlencoded'}),body:new URLSearchParams(data)});let j=await r.json();say(j.message);await refresh();return r.ok;}catch(e){say(t('lost'));}finally{busy=false;}}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if((b.dataset.action==='clean'||b.dataset.action==='empty')&&!confirm(t('askMove',b.textContent)))return;post('/api/command',{action:b.dataset.action});});
$('query').onclick=()=>post('/api/query',{});$('arm').onchange=()=>post('/api/arm',{enabled:$('arm').checked?'1':'0'});
$('setting').onchange=()=>{$('value').max=$('setting').value==='117'?60:120;};$('settings').onsubmit=e=>{e.preventDefault();post('/api/value',{dp:$('setting').value,value:$('value').value});};
async function refresh(){try{const r=await fetch('/api/state',{cache:'no-store',headers:{'X-Tonepie-Lang':LANG}});if(!r.ok)throw Error();const s=await r.json();token=s.token;last=Date.now();$('link').textContent=s.online?(s.ready?t('connected'):t('init')):t('offline');$('ip').textContent=s.ip;$('ssid').textContent=s.ssid;$('ap').textContent=s.recovery_ap?t('recovery'):'';$('arm').checked=s.armed;document.querySelectorAll('.write').forEach(b=>b.disabled=!s.armed||!s.ready||s.pending);$('command').textContent=s.command;$('dps').replaceChildren();for(const d of s.dps){const row=document.createElement('tr');for(const v of [d.id,d.label,d.type,d.value,Math.round(d.age_ms/1000)+' s']){let td=document.createElement('td');td.textContent=v;row.append(td);}$('dps').append(row);}$('state').textContent=s.dps.find(d=>d.id===24)?.value??t('notReceived');$('fault').textContent=s.dps.find(d=>d.id===22)?.value??t('notReceived');$('stats').textContent=t('stats',s);$('logs').textContent=s.logs.join('\n');if(!stateSeen){stateSeen=true;say(t('ready'));}}catch(e){$('link').textContent=t('dashOffline');document.querySelectorAll('.write').forEach(b=>b.disabled=true);}}
$('wifi').onsubmit=async e=>{e.preventDefault();if(busy||!confirm(t('askWifi',$('wifiSsid').value)))return;busy=true;try{const r=await fetch('/api/wifi',{method:'POST',headers:H({'X-Tonepie-Ota':$('wifiOta').value}),body:new URLSearchParams({ssid:$('wifiSsid').value,password:$('wifiPass').value})});say((await r.json()).message);}catch(e){say(t('wifiLost'));}finally{busy=false;$('wifiPass').value='';$('wifiOta').value='';}};
$('ota').onsubmit=async e=>{e.preventDefault();if(busy)return;const file=$('otaFile').files[0];if(!file||!confirm(t('askOta',file.name)))return;busy=true;say(t('sendingOta'));try{const body=new FormData();body.append('firmware',file);const r=await fetch('/api/update',{method:'POST',headers:H({'X-Tonepie-Ota':$('otaPass').value}),body});say((await r.json()).message);}catch(e){say(t('otaLost'));}finally{busy=false;$('otaPass').value='';}};
applyLang();document.querySelectorAll('.write').forEach(b=>b.disabled=true);refresh();setInterval(refresh,2000);
</script></body></html>)HTML";
