#pragma once
#include <Arduino.h>
const char WEB_UI[] PROGMEM = R"HTML(<!doctype html>
<html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tonepie · controllo locale</title><style>
:root{color-scheme:dark;--muted:#a9bbcb;--accent:#74dfca}*{box-sizing:border-box}body{margin:0;background:#0c1720;color:#eef5f8;font:16px system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:28px 18px}h1{font-size:32px;margin:8px 0}h2{font-size:20px;margin-top:0}.muted,small{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px}.card{background:#152630;border:1px solid #2b414d;border-radius:16px;padding:20px;margin:16px 0}.grid .card{margin:0}button,input,select{font:inherit;border-radius:8px;padding:11px;border:1px solid #48616f;background:#203947;color:white}button{cursor:pointer;margin:5px 5px 5px 0}button.primary{background:var(--accent);color:#09261e}button:disabled{opacity:.4;cursor:not-allowed}label{display:block;margin:12px 0}input[type=number],input[type=password],input[type=file],input:not([type]){width:100%}.metrics{display:flex;gap:20px;flex-wrap:wrap}.metric strong{display:block;font-size:23px}.table{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;border-bottom:1px solid #30444f;padding:10px;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:320px;overflow:auto;font-size:12px}#notice{position:sticky;bottom:12px;background:#234337;padding:14px;border-radius:10px;min-height:48px}.warning{color:#ffd792}a{color:var(--accent)}
</style></head><body><main><small>TONEPIE / TI PRO 25 · ESP-C3 · PAGINA SVILUPPATORE MCU · <a href="/">torna alla home</a></small><h1>Controllo locale</h1><p class="muted">La MCU originale gestisce movimenti e sensori. Mappatura comunitaria: da verificare sulla tua revisione.</p>
<section class="card metrics"><div class="metric"><small>Collegamento MCU</small><strong id="link">In attesa</strong></div><div class="metric"><small>Wi-Fi / IP</small><strong id="ip">—</strong></div><div class="metric"><small>Stato DP24 grezzo</small><strong id="state">Non ricevuto</strong></div><div class="metric"><small>Fault DP22 grezzo</small><strong id="fault">Non ricevuto</strong></div></section>
<div class="grid"><section class="card"><h2>Comandi</h2><p class="warning">Prima prova sorvegliata, lettiera senza animale. Un comando trasmesso non dimostra che il movimento sia avvenuto.</p><label><input id="arm" type="checkbox"> Abilita invii per 10 minuti</label><button class="primary write" data-action="clean">Pulizia manuale</button><button class="write" data-action="empty">Svuotamento</button><p><button class="write" data-action="auto_on">Auto-clean ON</button><button class="write" data-action="auto_off">Auto-clean OFF</button></p><button id="query">Aggiorna dalla MCU</button><p class="muted" id="command">Nessun comando</p><small>Gli invii richiedono un DP ricevuto con tipo corretto e recente. Nessun riavvio o bypass sensori.</small></section>
<section class="card"><h2>Tempi di pulizia</h2><form id="settings"><label>Impostazione<select id="setting"><option value="117">Attesa dopo uscita · DP117</option><option value="118">Intervallo minimo · DP118</option></select></label><label>Minuti<input id="value" type="number" min="0" max="60" value="5" required></label><button class="primary write" type="submit">Invia impostazione</button></form><p class="muted">DP117: 0–60 min. DP118: 0–120 min. Il valore attuale si legge nella tabella.</p></section></div>
<section class="card"><h2>Datapoint ricevuti</h2><small>ENUM è l'indice UART: non viene tradotto in nomi senza una verifica. Età = tempo dall'ultimo report.</small><div class="table"><table><thead><tr><th>DP</th><th>Indicazione comunitaria</th><th>Tipo UART</th><th>Valore</th><th>Età</th></tr></thead><tbody id="dps"></tbody></table></div><p id="stats" class="muted"></p></section>
<section class="card"><h2>Aggiornamento firmware via rete</h2><p class="muted">Carica il file <code>firmware.bin</code> compilato. Serve la password di aggiornamento scritta in <code>include/config.h</code>. Al termine il modulo si riavvia; dati di gatti e visite restano salvati.</p><form id="ota"><label>File<input id="otaFile" type="file" accept=".bin" required></label><label>Password di aggiornamento<input id="otaPass" type="password" autocomplete="off" required></label><button class="primary" type="submit">Aggiorna firmware</button></form></section>
<section class="card"><h2>Rete Wi-Fi</h2><p class="muted">Rete attuale: <b id="ssid">—</b><span id="ap"></span>. Se il Wi-Fi di casa resta irraggiungibile per 3 minuti il modulo apre la rete di recupero <code>Tonepie-Setup</code> (stessa password del Wi-Fi scritto nel firmware): collegati e apri <code>http://192.168.4.1/dev</code>.</p><form id="wifi"><label>Nome della nuova rete<input id="wifiSsid" maxlength="32" required></label><label>Password della rete<input id="wifiPass" type="password" minlength="8" maxlength="63" autocomplete="off" required></label><label>Password di aggiornamento<input id="wifiOta" type="password" autocomplete="off" required></label><button class="primary" type="submit">Salva rete e riavvia</button></form></section>
<section class="card"><h2>Log seriale recente</h2><p class="muted">Frame RX/TX validi, errori e rete · estratti hex fino a 64 byte · ultimi 60 eventi</p><pre id="logs"></pre></section><div id="notice" role="status" aria-live="polite">Connessione alla dashboard…</div></main>
<script>
let token='',busy=false,last=0;const $=id=>document.getElementById(id);const say=t=>$('notice').textContent=t;
async function post(path,data){if(busy)return;busy=true;try{let r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Tonepie-Token':token},body:new URLSearchParams(data)});let j=await r.json();say(j.message);await refresh();return r.ok;}catch(e){say('Connessione persa: non ripetere un movimento senza verificarlo sulla lettiera.');}finally{busy=false;}}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if((b.dataset.action==='clean'||b.dataset.action==='empty')&&!confirm('Avviare '+b.textContent+'? Verifica che la lettiera sia libera.'))return;post('/api/command',{action:b.dataset.action});});
$('query').onclick=()=>post('/api/query',{});$('arm').onchange=()=>post('/api/arm',{enabled:$('arm').checked?'1':'0'});
$('setting').onchange=()=>{$('value').max=$('setting').value==='117'?60:120;};$('settings').onsubmit=e=>{e.preventDefault();post('/api/value',{dp:$('setting').value,value:$('value').value});};
async function refresh(){try{const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw Error();const s=await r.json();token=s.token;last=Date.now();$('link').textContent=s.online?(s.ready?'Connessa':'Inizializzazione'):'Offline';$('ip').textContent=s.ip;$('ssid').textContent=s.ssid;$('ap').textContent=s.recovery_ap?' · rete di recupero attiva':'';$('arm').checked=s.armed;document.querySelectorAll('.write').forEach(b=>b.disabled=!s.armed||!s.ready||s.pending);$('command').textContent=s.command;$('dps').replaceChildren();for(const d of s.dps){const row=document.createElement('tr');for(const v of [d.id,d.label,d.type,d.value,Math.round(d.age_ms/1000)+' s']){let td=document.createElement('td');td.textContent=v;row.append(td);}$('dps').append(row);}$('state').textContent=s.dps.find(d=>d.id===24)?.value??'Non ricevuto';$('fault').textContent=s.dps.find(d=>d.id===22)?.value??'Non ricevuto';$('stats').textContent=`Frame: ${s.frames} · checksum errati: ${s.bad_checksum} · lunghezze errate: ${s.bad_length} · timeout: ${s.timeouts} · DP malformati: ${s.bad_dp} · RAM libera: ${s.heap} B · uptime: ${s.uptime_s} s · causa ultimo reset (codice ESP): ${s.reset_reason}`;$('logs').textContent=s.logs.join('\n');if($('notice').textContent==='Connessione alla dashboard…')say('Dashboard connessa. Invii inizialmente disabilitati.');}catch(e){$('link').textContent='Dashboard offline';document.querySelectorAll('.write').forEach(b=>b.disabled=true);}}
$('wifi').onsubmit=async e=>{e.preventDefault();if(busy||!confirm('Salvare la rete '+$('wifiSsid').value+' e riavviare?'))return;busy=true;try{const r=await fetch('/api/wifi',{method:'POST',headers:{'X-Tonepie-Token':token,'X-Tonepie-Ota':$('wifiOta').value},body:new URLSearchParams({ssid:$('wifiSsid').value,password:$('wifiPass').value})});say((await r.json()).message);}catch(e){say('Collegamento interrotto: il modulo si sta probabilmente riavviando.');}finally{busy=false;$('wifiPass').value='';$('wifiOta').value='';}};
$('ota').onsubmit=async e=>{e.preventDefault();if(busy)return;const file=$('otaFile').files[0];if(!file||!confirm('Sostituire il firmware con '+file.name+'?'))return;busy=true;say('Invio del firmware in corso: non chiudere la pagina…');try{const body=new FormData();body.append('firmware',file);const r=await fetch('/api/update',{method:'POST',headers:{'X-Tonepie-Token':token,'X-Tonepie-Ota':$('otaPass').value},body});say((await r.json()).message);}catch(e){say('Collegamento interrotto durante l\u2019aggiornamento: ricarica la pagina e controlla la versione.');}finally{busy=false;$('otaPass').value='';}};
document.querySelectorAll('.write').forEach(b=>b.disabled=true);refresh();setInterval(refresh,2000);
</script></body></html>)HTML";
