"""Draws the home-screen icon and writes it into include/icons.h.

    python tools/make_icons.py

The cat head is the same shape used by the home page. Icons are full-bleed
squares: iOS rounds the corners itself, Android masks them (the cat stays
inside the 80% safe zone of maskable icons).
"""
from pathlib import Path
import io

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
TOP, BOTTOM = (0xEF, 0x8A, 0x4A), (0xCF, 0x5A, 0x3E)
FACE = (0xFF, 0xFB, 0xF6)


def bezier(p0, p1, p2, p3, steps=24):
    out = []
    for i in range(1, steps + 1):
        t = i / steps
        u = 1 - t
        out.append((u**3 * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t**3 * p3[0],
                    u**3 * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t**3 * p3[1]))
    return out


def cat_outline():
    """The CAT svg path of web_home.h, in its 48x48 box."""
    pts = [(7, 8)]
    pts += bezier((7, 8), (7, 6.7), (8.5, 6), (9.5, 6.8))
    pts += [(18, 13.5)]
    pts += bezier((18, 13.5), (19.9, 12.9), (21.9, 12.6), (24, 12.6))
    pts += bezier((24, 12.6), (26.1, 12.6), (28.1, 12.9), (30, 13.5))
    pts += [(38.5, 6.8)]
    pts += bezier((38.5, 6.8), (39.5, 6), (41, 6.7), (41, 8))
    pts += [(41, 25)]
    pts += bezier((41, 25), (41, 34.4), (33.4, 41), (24, 41))
    pts += bezier((24, 41), (14.6, 41), (7, 34.4), (7, 25))
    return pts


def icon(size):
    s = size * 4  # supersampled, then reduced for smooth edges
    img = Image.new("RGB", (s, s))
    d = ImageDraw.Draw(img)
    for y in range(s):
        k = y / (s - 1)
        d.line([(0, y), (s, y)], fill=tuple(round(a + (b - a) * k) for a, b in zip(TOP, BOTTOM)))
    # Cat box x 7..41, y 6..41 -> 58% of the icon, centred.
    scale = s * 0.58 / 34
    ox, oy = s / 2 - 24 * scale, s / 2 - 23.8 * scale
    tr = lambda p: (ox + p[0] * scale, oy + p[1] * scale)
    d.polygon([tr(p) for p in cat_outline()], fill=FACE)
    eye = BOTTOM
    for cx in (17.5, 30.5):
        x, y = tr((cx, 25))
        r = 2.4 * scale
        d.ellipse([x - r, y - r, x + r, y + r], fill=eye)
    d.polygon([tr((21.6, 30.5)), tr((26.4, 30.5)), tr((24, 33.2))], fill=eye)
    img = img.resize((size, size), Image.LANCZOS)
    buf = io.BytesIO()
    img.quantize(colors=128, method=Image.MEDIANCUT, dither=Image.NONE).save(buf, "PNG", optimize=True)
    return buf.getvalue()


def array(name, data):
    rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 20]) for i in range(0, len(data), 20)]
    return f"const uint8_t {name}[] PROGMEM = {{\n" + ",\n".join(rows) + "\n};\n"


if __name__ == "__main__":
    parts = ["#pragma once\n#include <Arduino.h>\n// Generated by tools/make_icons.py: do not edit.\n"]
    for size in (180, 192, 512):
        data = icon(size)
        parts.append(array(f"ICON_{size}", data))
        print(f"icon {size}px: {len(data)} bytes")
    (ROOT / "include" / "icons.h").write_text("\n".join(parts), encoding="utf-8")
    Image.open(io.BytesIO(icon(512))).save(ROOT / "docs" / "images" / "app-icon.png")
